server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://49.235.90.145:3306/db_example?characterEncoding=utf8&serverTimezone=UTC
    username: demo
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml


