server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://49.235.90.145:3306/db_example?characterEncoding=utf8&serverTimezone=UTC
    username: demo
    password: qwer1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

